<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <UseWindowsForms>true</UseWindowsForms>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.1" />
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Forms\sanpham\Form_SanPham.cs">
        <SubType>Form</SubType>
      </Compile>
      <Compile Update="Forms\sanpham\Form_BangGia.cs">
        <SubType>Form</SubType>
      </Compile>
      <Compile Update="Forms\sanpham\Form_NguyenLieu.cs">
        <SubType>Form</SubType>
      </Compile>
      <Compile Update="Forms\kho\Form_CTPhieuNhap.cs">
        <SubType>Form</SubType>
      </Compile>
      <Compile Update="Forms\kho\Form_NhaCungCap.cs">
        <SubType>Form</SubType>
      </Compile>
      <Compile Update="Forms\kho\Form_PhieuNhap.cs">
        <SubType>Form</SubType>
      </Compile>
      <Compile Update="Form_Main.cs">
        <SubType>Form</SubType>
      </Compile>
    </ItemGroup>

</Project>